# Generated by Django 2.0.3 on 2018-03-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='user',
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='apellido'),
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
